---
- name: "Copie du repertoire Wordpress en le renommant avec la variable nomsite"
  command: mv /var/www/wordpress /var/www/{{ varnomsite }}.serverweb

- name: "Modification du propriétaire du repertoire nomsite"
  command: chown -R root:www-data /var/www/{{ varnomsite }}.serverweb

#- name: "Suppression des droits pour tous les autres utilisateurs"
#  command: chmod -R o-rwx /var/www/{{ varnomsite }}.serverweb
