---
- name: "Replace bdd name in wp-config.php"
  ansible.builtin.replace:
    path: /var/www/{{ varnomsite }}.serverweb/wp-config.php
    regexp: '(\.*)nombddsite(\.*)'
    replace: '\1{{ varnomsite }}\2'

- name: "Replace user name in wp-config.php"
  ansible.builtin.replace:
    path: /var/www/{{ varnomsite }}.serverweb/wp-config.php
    regexp: '(\.*)nombddadmin(\.*)'
    replace: '\1{{ varadminbdd }}\2'

- name: "Replace password in wp-config.php"
  ansible.builtin.replace:
    path: /var/www/{{ varnomsite }}.serverweb/wp-config.php
    regexp: '(\.*)motdepasse(\.*)'
    replace: '\1{{ varpasswdbd }}\2'

- name: "test autre moyen de rebooter"
  command: reboot
