---

# installation de wordpress via https
- name: Check that the somefile.conf exists
  stat:
    path: /var/tmp/wordpress.tar.gz
  register: stat_result

- name: "wordpress installation"
  get_url:
    url: https://fr.wordpress.org/latest-fr_FR.tar.gz
    dest: /var/tmp/wordpress.tar.gz
    validate_certs: no
  when: not stat_result.stat.exists

- name: "wordpress decompression"
  unarchive:
    src: /var/tmp/wordpress.tar.gz
    dest: /var/www/
    copy: no
