---
- name: "Création de la base de données ayant pour nom celui du site Wordpress"
  mysql_db:
    name: "{{ varnomsite }}"
    state: present

- name: "Création du compte administrateur de cette base de données"
  mysql_user:
    name: "{{ varadminbdd }}"
    password: "{{ varpasswdbd }}"
    host: 192.168.106.2
    priv: '{{ varnomsite }}.*:ALL,GRANT'
    state: present

- name: "Activation des privilèges pour cette base de données"
  community.mysql.mysql_query:
    login_db: "{{ varnomsite }}"
    query: FLUSH PRIVILEGES

- name: "Redémarrage du serveur de base de données"
  reboot:
