---
- name: "Create a new database"
  mysql_db:
    name: "{{ varnomsite }}"
    state: present

- name: "Create a new user"
  mysql_user:
    name: "{{ varadminbdd }}"
    password: "{{ varpasswdbd }}"
    host: 192.168.106.2
    priv: '{{ varnomsite }}.*:ALL,GRANT'
    state: present

- name: "Query flush"
  community.mysql.mysql_query:
    login_db: "{{ varnomsite }}"
    query: FLUSH PRIVILEGES

- name: Unconditionally reboot the machine with all defaults
  reboot:
