---

#CONFIGURATION DE NGINX

- name: "activer option server tokens dans le fichier de conf"
  ansible.builtin.replace:
    path: /etc/nginx/nginx.conf
    regexp: '# server_tokens'
    replace: 'server_tokens'

- name: "copier le template vhost et modifier son nom avec la variable nomsite"
  copy:
    src: /etc/ansible/roles/config_nginx/files/nomsite
    dest: /etc/nginx/sites-available/{{ varnomsite }}

- name: "remplacer les données relatives à php-wp"
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/{{ varnomsite }}
    regexp: '(\.*)php-wp(\.*)'
    replace: '\1php-wp-{{ varnomsite }}\2'

- name: "remplacer les données relatives à nomsite pour la socket"
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/{{ varnomsite }}
    after: '    server            unix:/var/run/'
    before: '.sock'
    regexp: 'nomsite'
    replace: '{{ varnomsite }}'

- name: "remplacer les données relatives à nomsite pour le nom du serveur"
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/{{ varnomsite }}
    after: '    server_name       '
    before: '.serverweb'
    regexp: 'nomsite'
    replace: '{{ varnomsite }}'

- name: "remplacer les données relatives à nomsite pour le chemin racine"
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/{{ varnomsite }}
    after: '    root              /var/www/'
    before: '.serverweb'
    regexp: 'nomsite'
    replace: '{{ varnomsite }}'

- name: "creation du lien symbolique"
  command: ln -s /etc/nginx/sites-available/{{ varnomsite }} /etc/nginx/sites-enabled/
