---

#CONFIGURATION DE NGINX

- name: "activaction de l'option server tokens dans le fichier de configuration de Nginx"
  ansible.builtin.replace:
    path: /etc/nginx/nginx.conf
    regexp: '# server_tokens'
    replace: 'server_tokens'

- name: "copie du vhost dans le répertoire des sites web disponible de Nginx et modification de son nom en fonction du nom de site choisi"
  copy:
    src: /etc/ansible/roles/config_nginx/files/nomsite
    dest: /etc/nginx/sites-available/{{ varnomsite }}

- name: "remplacement des données relatives aux variables de nom du site pour le module php-wp du vhost"
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/{{ varnomsite }}
    regexp: '(\.*)php-wp(\.*)'
    replace: '\1php-wp-{{ varnomsite }}\2'

- name: "remplacement des données relatives aux variables de nom du site pour la socket du vhost"
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/{{ varnomsite }}
    after: '    server            unix:/var/run/'
    before: '.sock'
    regexp: 'nomsite'
    replace: '{{ varnomsite }}'

- name: "remplacement des données relatives aux variables de nom du site pour le nom du serveur dans le vhost"
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/{{ varnomsite }}
    after: '    server_name       '
    before: '.serverweb'
    regexp: 'nomsite'
    replace: '{{ varnomsite }}'

- name: "remplacement des données relatives aux variables de nom du site pour le chemin racine dans le vhost"
  ansible.builtin.replace:
    path: /etc/nginx/sites-available/{{ varnomsite }}
    after: '    root              /var/www/'
    before: '.serverweb'
    regexp: 'nomsite'
    replace: '{{ varnomsite }}'

- name: "creation du lien symbolique qui passe le vhost en site actif dans Nginx"
  command: ln -s /etc/nginx/sites-available/{{ varnomsite }} /etc/nginx/sites-enabled/
