---
- name: "copie du template pool php et modification de son nom avec la variable de nom du site"
  copy:
    src: /etc/ansible/roles/config_php/files/nomsite.conf
    dest: /etc/php/7.3/fpm/pool.d/{{ varnomsite }}.conf

- name: "remplacement du nom de pool avec la variable de nom de site"
  ansible.builtin.replace:
    path: /etc/php/7.3/fpm/pool.d/{{ varnomsite }}.conf
    regexp: '(\.*)nomsite(\.*)'
    replace: '\1{{ varnomsite }}\2'

- name: "remplacement des données relatives au nom du site pour la socket du pool"
  ansible.builtin.replace:
    path: /etc/php/7.3/fpm/pool.d/{{ varnomsite }}.conf
    after: 'listen = /var/run/'
    before: '.sock'
    regexp: 'nomsite'
    replace: '{{ varnomsite }}'

- name: "copie du template wp-config.php dans le répertoire du site Wordpress"
  copy:
    src: /etc/ansible/roles/config_php/files/wp-config.php
    dest: /var/www/{{ varnomsite }}.serverweb/wp-config.php
